name: Deploy API

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t maroua321/weather-api:latest --build-arg API_KEY=${{ env.API_KEY }} -f ./Dockerfile.api .
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: maroua321
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Push Docker image
        run: |
          docker push maroua321/weather-api:latest
