FROM python:3.9

COPY requirements.txt /app/
WORKDIR /app

RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app

CMD ["gunicorn", "-b", "0.0.0.0:5000", "weather_api:app"]
