name: build-and-deploy

on:
  push:
    branches: [ main ]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t 20211183:latest .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: maroua321
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag 20211183:latest maroua321/20211183:latest
        docker push maroua321/20211183:latest
