name: deploy-api-on-azure

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_REGISTRY: efreidevops.azurecr.io
  ACI_NAME: 20211183
  RESOURCE_GROUP: ADDA84-CTP

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          credentials: ${{ env.AZURE_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: maroua123
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build and push image'
        env:
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          docker build . -t $REGISTRY_LOGIN_SERVER/20211183:v1
          docker login $REGISTRY_LOGIN_SERVER -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          docker push $REGISTRY_LOGIN_SERVER/20211183:v1

      - name: Deploy to Azure Container Instance
        uses: azure/container-action@v1
        with:
          image: ${{ secrets.ACR_REGISTRY }}/20211183:v1
          name: ${{ secrets.ACI_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-20211183
          location: francecentral
          ports: 8081:8081
