name: deploy-api-on-azure

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_REGISTRY: efreidevops.azurecr.io
  ACI_NAME: 20211183
  RESOURCE_GROUP: ADDA84-CTP

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_REGISTRY }}/11002167:v1 .
          docker push ${{ env.ACR_REGISTRY }}/11002167:v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Deploy to Azure Container Instance
        uses: azure/container-action@v1
        with:
          image: ${{ env.ACR_REGISTRY }}/20211183:v1
          name: ${{ env.ACI_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          dns-name-label: devops-20211183
          location: francecentral
          ports: 8081:8081
