name: build-and-deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_REGISTRY: efreidevops.azurecr.io
  ACI_NAME: 20211183
  RESOURCE_GROUP: ADDA84-CTP

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_REGISTRY }}/20211183:v1 .
          docker push ${{ env.ACR_REGISTRY }}/20211183:v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACI_NAME }} --image ${{ env.ACR_REGISTRY }}/20211183:v1 --dns-name-label devops-20211183 --ports 8081 --cpu 1 --memory 1.5 --restart-policy Never
